# Site
name: "Mas Cemplon"
title: "Mas Cemplon"
description: "Berbagi Informasi Onlien Yang Mendidik"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ""
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'postkomik-github-1'
mailchimp-list: 'https://us7.campaign-archive.com//subscribe/post?u=7ea9767765c64bad4a7615b18&id=32b78086cf&e=[UNIQID]'
include: ["_pages"]
permalink: /:title/
email: Ahmadalwy@gmail.com

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/avatar.png'
    email: wowthemesnet@gmail.com
    web: www.google.com
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
    
  mas cemplon:
    name: Mas Cemplon
    display_name: Mas Cemplon
    avatar: 'assets/images/avatar.png'
    email: Ahmadalwy@gmail.com
    web: https://postkomik.github.io
    twitter: https://twitter.com/
    description: "Author of postkomik, a Manga Mahua styled template available for Blogger, HTML, . You are currently previewing Website."
    
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: www.google.com
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

#exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
